name = "GappedKmers"
authors = ["Datanagan, Kyrstin <mcquiddk@oregonstate.edu>", "Cory Simon <cory.simon@oregonstate.edu>"]
uuid = "2048ae2c-aa03-11ef-10c5-b56aa5cb0ed2"
version = "0.0.1"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
