name = "GappedKmers"
authors = ["Datanagan, Kyrstin <mcquiddk@oregonstate.edu>", "Cory Simon <cory.simon@oregonstate.edu>"]
version = "0.0.1"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
julia = "1.8"
BioSequences = "3.1.6"
IterTools = "1.10.0"
DataFrames = "1.6.1"

[extras]
